### PR TITLE
Fix/more attributes

### PR DESCRIPTION
**Pull request by KrzysztofHajdamowicz**
This Pull Request includes improvements created by @kovbalazs89, @pierosavi and @bashau

### CODE REVIEW

**Comment by pierosavi** [comment]
40f4f37 doesn't work as expected, it was more of a test on my side.
It was fixed in the next commit: https://github.com/pierosavi/home-assistant-vacuum-styj02ym/commit/e467a9a432dedd9da88101733a96b46b92f8344d

Keep in mind I did those to support https://github.com/denysdovhan/vacuum-card
The vacuum sensor will have duplicate attributes because of that

**Comment by KrzysztofHajdamowicz** [comment]
> [40f4f37](https://github.com/KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym/commit/40f4f37f18fa95d1e0430de9410967b16043effa) doesn't work as expected, it was more of a test on my side.
> It was fixed in the next commit: [pierosavi@e467a9a](https://github.com/pierosavi/home-assistant-vacuum-styj02ym/commit/e467a9a432dedd9da88101733a96b46b92f8344d)
> 
> Keep in mind I did those to support https://github.com/denysdovhan/vacuum-card
> The vacuum sensor will have duplicate attributes because of that

Hi!
Thanks for Your feedback! I will merge this one as well!

**Comment by KrzysztofHajdamowicz** [comment]
@pierosavi Your code is merged here: https://github.com/KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym/commit/36997a6c5c41b8530d11dedaf269d2caa036bd62

**Comment by pierosavi** [comment]
@KrzysztofHajdamowicz 
The newest version of https://github.com/denysdovhan/vacuum-card has a stats object, that makes my fork useless (except the more attributes thing) and adds duplicate attributes for nothing
I don't suggest merging it

**Pull request merged**
